---
title: "02v2_interpolation"
author: "Arthur de Grandpré"
date: "30 juillet 2020"
output: html_document
---
```{r setup}

rm(list=ls())

library(raster)
library(rgdal)
# library(rgeos)
library(sf)
library(leaflet)
library(mapview)
library(tidyverse)
library(lubridate)
library(zoo)
```


# Data validation

Let's load the better fitted data as of the .nc files extraction, look at it's structure and format it conveniently.

```{r read_data}
df = read.csv("./data/simspec2020.csv")
summary(df)
df[,c(1,2)]=NULL
df$date = lubridate::ymd(df$date)
colnames(df) = c("x","y","b1","b2","b3","b4","b5","b6","b7","b8","b8a","b11","b12","date","satellite","pond","class")

sfd = sf::st_as_sf(df, coords = c("x","y"))
sfd = st_set_crs(sfd, 4326)
```

```{r spatialfit_validation}
d1 = sfd[sfd$date==unique(sfd$date)[1],]
plot(d1[1],main=paste0("test: B8 on ",d1$date[1]))

pal = colorNumeric(
  palette = "RdYlGn",
  domain = d1$b8
)

leaflet(d1) %>%
  addTiles() %>% 
  addCircleMarkers(stroke = F,
                   fillColor = ~pal(b8),
                   fillOpacity = 0.5,
                   radius = 8) 

```

```{r npixel_validation}
val_df = sfd %>% group_by(date,pond) %>% summarise(frequency = n()) %>% ungroup

ggplot(val_df, aes(x=date, y=frequency, group=pond)) +
  geom_point()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  facet_wrap(~pond)

```

```{r}
sfd2 = sfd
sfd2 = sfd2 %>% 
  mutate_at(vars(c(1:11,15)), funs(ifelse(class=="clouds",NA,.)))
sfd2$x = st_coordinates(sfd2)[,1]
sfd2$y = st_coordinates(sfd2)[,2]
sfd2$xy = paste0(sfd2$x,"_",sfd2$y)
df3 = st_drop_geometry(sfd2)
# need one column per XY coordinate per band, one line per date, and then fill NAs using previous known values
df3$class[df3$class==2]="vegetation"
df3$class[df3$class==3]="water"

df3s = df3 %>% 
  filter(xy==unique(xy[1])) %>% 
  mutate(date, lubridate::ymd(date)) %>% 
  arrange(date)
  
df3s[,1:11] = na.locf(df3s[,1:11], maxgap=4, na.rm=FALSE)



  
for(i in 2:length(unique(df3$xy))){
  print(paste0("point ",i," out of ",length(unique(df3$xy))))
  df3si = df3 %>% 
    filter(xy==unique(xy[i])) %>% 
    mutate(date, lubridate::ymd(date)) %>% 
    arrange(date)
  
  df3si[,1:11] = na.locf(df3si[,1:11], maxgap=4, na.rm=FALSE)
  df3s=rbind(df3s,df3si)
}

df3c = df3s

cloud_treshold = 0.3
vegetation_treshold= 0.08

df3c$class = ifelse(df3c$b2 < cloud_treshold,
                   ifelse(df3c$b8 > vegetation_treshold,
                          "vegetation",
                          "water"),
                   "clouds")

df3c = df3c[complete.cases(df3c),]

ggplot(df3c, aes(x=class)) +
  geom_bar()

edf1 = df3c %>% group_by (pond, date, class) %>%
  summarise(pixels = n()) %>%
  ungroup()

edf2 = df3c %>% group_by (pond, date) %>% 
  summarise(tot_pixels = n()) %>% 
  ungroup()

edf3 = left_join(edf1,edf2) %>% 
  filter(class == "vegetation") %>% 
  mutate(em_veg = pixels/tot_pixels)

ggplot(edf3, aes(x=date, y=em_veg, group=pond)) +
  geom_point()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  facet_wrap(~pond)

write.csv(edf3, "./data/emerging_vegetation_simspec.csv")
```
